spring:
  datasource:
    url: jdbc:mysql://192.168.61.45:3306/springbootdemo?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: fulsun
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
## 日志级别
logging:
  level:
    top:
      fulsun:
        mapper: debug

mybatis:
  type-aliases-package: top.fulsun.entity
  ## 检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
  # check-config-location: true
  ## 配置文件位置
  # config-location: classpath:mybatis/mybatis-config.xml
  ## mapper xml文件地址
  # mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    ## 开启mybatis驼峰命名映射，不然取得时间的值为空-->
    map-underscore-to-camel-case: true